# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Mohammad Saad
url:              https://mohsaad.com
baseurl:          /

real_url:         https://www.mohsaad.com

author:
  name:           'Mohammad Saad'
  url:            https://twitter.com/mohsaad230

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/mohsaad

plugins: [jekyll-paginate]

exclude: [drafts]
